set -U FZF_LEGACY_KEYBINDINGS 0
set -U PYENV_ROOT '/home/akihide/.pyenv'
set -x EDITOR '/usr/bin/nvim'
set -x BROWSER '/usr/bin/google-chrome-stable'
set -x GOPATH '/home/akihide/Repositories/go'
set -x PATH $PATH $GOPATH/bin 
alias nshift='redshift -x && redshift -O 2500 && xbacklight -set 0.05'
alias scf='source ~/.config/fish/config.fish'
alias cf='nvim ~/.config/fish/config.fish'
alias i3config='nvim ~/.i3/config'
alias cx='nvim ~/.Xresources'
alias sx='startx'
alias sp='sudo pacman'
alias sps='sudo pacman -S'
alias yays='yay -S'
alias windows='qemu-system-x86_64 -enable-kvm -usb -device usb-tablet -m 2048 -smp 2 -hda /var/lib/libvirt/images/win10.qcow2&'
alias hdmi='xrandr --output HDMI1 --auto --above eDP1'
alias hdmioff='xrandr --output HDMI1 --off'
alias nn='nvim'
alias n.='nvim .'
